// Generated by scripts/gen_tokens.py from docs/design-system/tokens.json. Do not edit by hand.
// Axis Gray: Axis Gray, version 1

import SwiftUI

enum Tokens {
    enum Colors {
        /// Screen background. Flat warm gray.
        static let ground = Color(.sRGB, red: 0.8588, green: 0.8549, blue: 0.8471, opacity: 1)
        /// Cards and sheets, one step lighter than ground.
        static let surface = Color(.sRGB, red: 0.9059, green: 0.902, blue: 0.8902, opacity: 1)
        /// Primary text and the main action button. 12:1 on ground.
        static let ink = Color(.sRGB, red: 0.102, green: 0.102, blue: 0.098, opacity: 1)
        /// Secondary text and mono labels. 5:1 on ground.
        static let muted = Color(.sRGB, red: 0.3686, green: 0.3569, blue: 0.3451, opacity: 1)
        /// 1px borders and dividers. Dashed for list dividers and chart guides.
        static let hairline = Color(.sRGB, red: 0.102, green: 0.102, blue: 0.098, opacity: 0.16)
        /// Squircle icon buttons with a white glyph.
        static let taupe = Color(.sRGB, red: 0.5569, green: 0.5216, blue: 0.5176, opacity: 1)
        /// Work phase: timer, label, progress line. Red from the reference gradient, deepened for 5:1 on ground.
        static let work = Color(.sRGB, red: 0.7255, green: 0.2275, blue: 0.149, opacity: 1)
        /// Recover phase: timer, label, progress line. Graphite gray, 7:1 on ground.
        static let recover = Color(.sRGB, red: 0.2902, green: 0.2784, blue: 0.2745, opacity: 1)
        /// Gradient blob and focus dot only. Never a button fill. Sampled from the reference gradient.
        static let signal = Color(.sRGB, red: 0.7686, green: 0.2627, blue: 0.1686, opacity: 1)
        /// Second stop of the signal gradient. Decoration only.
        static let ember = Color(.sRGB, red: 0.851, green: 0.5412, blue: 0.2314, opacity: 1)
    }

    enum Spacing {
        /// Icon gaps.
        static let space1: CGFloat = 4
        /// Tight stacks.
        static let space2: CGFloat = 8
        /// Row padding and gaps.
        static let space3: CGFloat = 16
        /// Screen side margin.
        static let space4: CGFloat = 20
        /// Section gaps and bottom safe margin.
        static let space5: CGFloat = 32
    }

    enum Radius {
        /// Icon buttons and steppers (continuous corners).
        static let radiusButton: CGFloat = 16
        /// Cards, sheets and preview panels.
        static let radiusCard: CGFloat = 20
        /// Main action button, 72px tall.
        static let radiusPill: CGFloat = 36
    }

    enum Typography {
        static let numeralXl = TypeToken(fontName: "Michroma-Regular", size: 112, lineHeight: 112, tracking: -0.02)
        static let numeralLg = TypeToken(fontName: "Michroma-Regular", size: 80, lineHeight: 80, tracking: -0.02)
        static let numeralMd = TypeToken(fontName: "Michroma-Regular", size: 26, lineHeight: 30, tracking: -0.01)
        static let numeralSm = TypeToken(fontName: "Michroma-Regular", size: 15, lineHeight: 20, tracking: 0)
        static let title = TypeToken(fontName: "Michroma-Regular", size: 24, lineHeight: 30, tracking: 0.01)
        static let phase = TypeToken(fontName: "Michroma-Regular", size: 13, lineHeight: 18, tracking: 0.04)
        static let body = TypeToken(fontName: "HankenGrotesk-Light", size: 17, lineHeight: 24, tracking: 0)
        static let button = TypeToken(fontName: "HankenGrotesk-SemiBold", size: 20, lineHeight: 24, tracking: 0)
        static let label = TypeToken(fontName: "HankenGrotesk-Medium", size: 11, lineHeight: 16, tracking: 0.06)
    }
}
