#!/usr/bin/env python3
"""Generate HIDIT/DesignSystem/Tokens.swift and the Ground launch color from docs/design-system/tokens.json.

Run from the repo root after the design system changes:  python3 scripts/gen_tokens.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "design-system", "tokens.json")
OUT = os.path.join(ROOT, "HIDIT", "DesignSystem", "Tokens.swift")
COLORSET = os.path.join(ROOT, "HIDIT", "Resources", "Assets.xcassets", "Ground.colorset", "Contents.json")

# PostScript names of the bundled font files, by token family and weight.
FONT_FILES = {
    ("display", 400): "Michroma-Regular",
    ("sans", 300): "HankenGrotesk-Light",
    ("sans", 400): "HankenGrotesk-Regular",
    ("sans", 500): "HankenGrotesk-Medium",
    ("sans", 600): "HankenGrotesk-SemiBold",
}


def camel(name):
    parts = re.split(r"[-_.]", name)
    out = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return "_" + out if out[0].isdigit() else out


def rgba(value):
    value = value.strip()
    m = re.fullmatch(r"#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?", value)
    if m:
        h = m.group(1)
        a = int(m.group(2), 16) / 255 if m.group(2) else 1.0
        return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a
    m = re.fullmatch(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)", value)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3)), float(m.group(4) or 1)
    raise ValueError("Unsupported color: " + value)


def px(value):
    return float(str(value).replace("px", ""))


def em(value):
    return float(str(value).replace("em", "")) if value is not None else 0.0


def fmt(x):
    s = ("%.4f" % x).rstrip("0").rstrip(".")
    return s if s else "0"


def main():
    with open(SRC) as f:
        tokens = json.load(f)
    lines = [
        "// Generated by scripts/gen_tokens.py from docs/design-system/tokens.json. Do not edit by hand.",
        "// Axis Gray: " + tokens.get("name", "") + ", version " + str(tokens.get("version", "")),
        "",
        "import SwiftUI",
        "",
        "enum Tokens {",
        "    enum Colors {",
    ]
    theme = tokens["color"]["themes"][0]["id"]
    ground = None
    for t in tokens["color"]["tokens"]:
        v = t["value"][theme] if isinstance(t["value"], dict) else t["value"]
        r, g, b, a = rgba(v)
        if t["name"] == "ground":
            ground = (r, g, b, a)
        lines.append("        /// " + t.get("usage", ""))
        lines.append(
            "        static let %s = Color(.sRGB, red: %s, green: %s, blue: %s, opacity: %s)"
            % (camel(t["name"]), fmt(r / 255), fmt(g / 255), fmt(b / 255), fmt(a))
        )
    lines += ["    }", "", "    enum Spacing {"]
    for t in tokens["spacing"]["tokens"]:
        lines.append("        /// " + t.get("usage", ""))
        lines.append("        static let %s: CGFloat = %s" % (camel(t["name"]), fmt(px(t["value"]))))
    lines += ["    }", "", "    enum Radius {"]
    for t in tokens["radius"]["tokens"]:
        lines.append("        /// " + t.get("usage", ""))
        lines.append("        static let %s: CGFloat = %s" % (camel(t["name"]), fmt(px(t["value"]))))
    lines += ["    }", "", "    enum Typography {"]
    for group in tokens["type"]["groups"]:
        family = group["family"]
        for s in group["styles"]:
            weight = int(str(s.get("fontWeight", 400)).split()[0])
            font = FONT_FILES.get((family, weight))
            if font is None:
                raise ValueError("No bundled font for %s %d" % (family, weight))
            size = px(s["fontSize"])
            lh = px(s.get("lineHeight", s["fontSize"]))
            lines.append(
                '        static let %s = TypeToken(fontName: "%s", size: %s, lineHeight: %s, tracking: %s)'
                % (camel(s["name"]), font, fmt(size), fmt(lh), fmt(em(s.get("letterSpacing"))))
            )
    lines += ["    }", "}", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    if ground:
        r, g, b, a = ground
        colorset = {
            "colors": [{
                "color": {"color-space": "srgb", "components": {
                    "red": "0x%02X" % r, "green": "0x%02X" % g, "blue": "0x%02X" % b, "alpha": fmt(a)}},
                "idiom": "universal",
            }],
            "info": {"author": "xcode", "version": 1},
        }
        os.makedirs(os.path.dirname(COLORSET), exist_ok=True)
        with open(COLORSET, "w") as f:
            json.dump(colorset, f, indent=2)
            f.write("\n")
    print("Wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
